### PR TITLE
Fix race condition in test and other test bugs

### LINKED ISSUE #161: Tests won't complete unless -race is used
I was trying to run the tests in libhoney-go, and the TestHoneycombTransmissionFlush test never terminates for me (unless killed by a timeout). But if you run it under the race detector (-race) it works just fine. 

Dean said "race detector slows everything down. if there's a race where something being fast makes it deadlock…"
**Versions**

- Go: 1.17.2
- Libhoney: 1.15.6

**Steps to reproduce**

1. run `go test -timeout 30s -count=1 ./...` -- it will generate a stack trace after 30 sec
2. run `go test -timeout 30s -count=1 -race ./...`

**Additional context**
I'm going to look at adding some sleeps to the test to see if it is in fact a deadlock.

### PR DESCRIPTION
**Pull request by kentquirk**
## Which problem is this PR solving?
This fixes #161 and a couple of other issues discovered while debugging it. 

The immediate problem is that running the test under `-race` worked on my machine, while running without it hung forever. 

## Short description of the changes

- There was a race condition in the assumptions made by the test code -- the test code needed Add() to run before Flush() but on a fast machine, it might not finish in time. (It was confusing to debug because the test code is trying to induce potential race conditions!)
- There was an assertion in a test comment that a write to a nil channel would panic, but in fact, a write to a nil channel blocks forever. I changed the test to use a closed channel instead, which *will* panic if it occurs.
- Two successive statements attempted to log the same value (the length of a queue), but under concurrency they might not be the same value, so I added a temp var.

### CODE REVIEW

File: transmission/transmission_test.go [hunk 1]
```diff
@@ -924,18 +924,25 @@ func TestHoneycombTransmissionFlush(t *testing.T) {
...
 			t.Error("unable to start", err)
 		}
 		defer w.Stop()
 
+		// This call wants the Add to run first, and then make sure that the Flush doesn't lose the data.
+		// But on a fast machine, the Add might actually be interrupted by the Flush, and then correctly add the
+		// data to the *second* queue -- which is correct, but not what the test is looking for. So we'll
+		// give the Add a few msec to run first.
 		w.Add(ev)
+		time.Sleep(50 * time.Millisecond)
```
Comment (vreynolds) [inline transmission/transmission_test.go:945]: I think we can use metrics to wait for the `Add` deterministically (wait for `messages_queued` to be the right number), but it's probably not worth the hassle of setting up metrics, eh?

Comment (kentquirk) [reply transmission/transmission_test.go:945]: I actually tried that, but it failed because the metrics are updated *before* the item is added to the queue. So you can still see deadlocks sometimes. This way isn't pretty but I haven't had it fail yet.

**Review by vreynolds — APPROVED** [review]

File: transmission/transmission_test.go (hunk 1 above)
Comment (robbkidd) [reply transmission/transmission_test.go:945]: Rubbin' some sleep on it.

tenor-243394000
